### PR TITLE
Add warning message at public username registration fail in Wizard

### PR DESCRIPTION
**Pull request by moustafine**

### CODE REVIEW

**Comment by Elv13** [comment]
Merged, thanks.

About that build failure. Please get a KDE account (say I sponsor you). That way you will be able to fix future build failures as they happen. Ring depends on many things. Of course there's always a risk someone come to fix a compliance or traduction bug and breaks things. At some point we had a CI system, but Ring-KDE got too complex to build once libringclient left KDE for GNU. You did great work so far, I trust you that you will keep doing so. Better getting a real commit access now instead of playing the GitHub ping pong game for work that's often superior than the code around it ;).

LibRingClient is where the (my) good code went. Ring-KDE was where the new features were tested before landing in the Gnome/Windows/OSX/Android/iOS/Metro clients. It's why it has so many more features than the other clients (mostly security and contact* ones)

About the code, very good, as usual. One thing I noted, but isn't important is that C++11 allows to set the value of an attribute directly in the class definition `bool usernameValid {false};` or `bool usernameValid = false;`. This is better when an attributes default value doesn't depend on the constructor argument as it prevent some uninitialized bugs (there is a warning, but some might ignore it). But again, this is so minor I didn't even bothered to edit the commit.

Thanks for this! 

/* If Akonadi is enabled. The fallback vCard backend is good enough, but has a lot less features than the real deal. But I aknoledge many users don't want to turn on Akonadi, so I implemented a fallback.

**Comment by ArchangeGabriel** [comment]
I’m making use of this discussion because I’m not sure what the right place is, but does Ring KDE client works for you? I’m having a `Status 200` error in the account settings.

**Comment by Elv13** [comment]
> I’m not sure what the right place is

There is no right place anymore since the Ring bug tracker stopped caring about KDE. I should open one on `bugs.kde.org`, but I don't have time at all right now.

Yes, it does work for me. Could you please launch the ring daemon (called `dring`) manually with `-c -d`. Then, in another terminal, start the KDE client.  Attach the result of both process logs here (make sure it doesn't contains personal information). I should be able to figure out whats wrong. You could also try with the Gnome client. If it works there, then its really my problem and I will fix it.

**Comment by ArchangeGabriel** [comment]
Maybe you could (temporarily) open issues on GitHub also.

Below are my logs, I’ve replaced the username with <user> and the Ring account UID (or hash, or whatever that is) with <accountUID>. Some other things have been obfuscated that way.

Daemon log:
```
Ring Daemon 3.0.0-e0f5c89bb8-dirty, by Savoir-faire Linux 2004-2016
http://www.ring.cx/
[Video support enabled]

[1482719522.029|25416|ringbufferpool.cpp:115  ] Ringbuffer created with id 'audiolayer_id'
[1482719522.029|25416|account_factory.cpp:40  ] registered SIP account
[1482719522.029|25416|account_factory.cpp:43  ] registered RING account
[1482719522.031|25416|manager.cpp:219         ] Not initialized
[1482719522.031|25416|manager.cpp:219         ] Not initialized
03:32:02.031 os_core_unix.c !pjlib 2.5.5 for POSIX initialized
[1482719522.031|25416|manager.cpp:303         ] pjsip version 2.5.5 for linux initialized
[1482719522.031|25416|manager.cpp:306         ] GNU TLS version 3.4.17 initialized
[1482719522.032|25416|ice_transport.cpp:85    ] [ice] added host stun server
[1482719522.032|25416|ice_transport.cpp:85    ] [ice] added host stun server
[1482719522.032|25416|manager.cpp:313         ] Configuration file path: /home/<user>/.config/ring/dring.yml
[1482719522.039|25416|system_codec_container.cpp:151] Encoders found: H264 VP8 MP4V-ES H263-1998 opus G722 speex speex speex PCMA PCMU 
[1482719522.039|25416|system_codec_container.cpp:152] Decoders found: H264 VP8 MP4V-ES H263-1998 opus G722 speex speex speex PCMA PCMU 
[1482719522.039|25418|upnp_context.cpp:122    ] NAT-PMP: initialized
[1482719522.090|25416|upnp_context.cpp:181    ] UPnP: using IPv4
[1482719522.090|25416|upnp_context.cpp:185    ] UPnP: initialiazed on <localIP>:<somehighportnumber>
[1482719522.893|25416|sipvoiplink.cpp:507     ] Using SIP nameserver: 127.0.0.1
[1482719522.893|25416|sipvoiplink.cpp:507     ] Using SIP nameserver: 127.0.0.1
[1482719522.893|25416|siptransport.cpp:185    ] SipTransportBroker@0x7beab0
[1482719523.548|25416|sipvoiplink.cpp:588     ] SIPVoIPLink@0x7f1e10
[1482719523.548|25416|namedirectory.cpp:336   ] Could not load /home/<user>/.cache/ring/namecache/ns.ring.cx
[1482719523.548|25416|ringaccount.cpp:1191    ] RingAccount::loadAccount
[1482719523.548|25416|ringaccount.cpp:792     ] loadIdentity() /home/<user>/.local/share/ring/<accountUID>/dht.crt /home/<user>/.local/share/ring/<accountUID>/dht.key
[1482719523.551|25416|ringaccount.cpp:2129    ] Could not load /home/<user>/.local/share/ring/<accountUID>/knownDevices
[1482719523.551|25416|ringaccount.cpp:2211    ] Error loading devices: Can't read file: /home/<user>/.local/share/ring/<accountUID>/knownDevicesNames
[1482719523.551|25416|ringaccount.cpp:1206    ] Password needed to create archive
[1482719523.552|25416|sipaccount.cpp:1699     ] Presence enabled for IP2IP : false.
[1482719533.399|25422|upnp_context.cpp:764    ] UPnP: checking new device of type IGD: '<routerNetworkName>'
[1482719533.417|25422|upnp_context.cpp:850    ] UPnP: got external IP: <publicIP>
[1482719533.419|25422|upnp_context.cpp:871    ] UPnP: found a valid IGD: http://<routerPrivateIP>:<someport>/<somehash>/gatedesc1.xml
[1482719533.419|25422|upnp_context.cpp:1171   ] UPnP: removing all port mappings with description: "RING" and local ip: <localIP>
[1482719533.428|25422|upnp_context.cpp:1191   ] UPnP: Failed to get GetGenericPortMappingEntry from: urn:schemas-upnp-org:service:WANIPConnection:1, 713: Unknown error code
[1482719575.359|25416|certstore.cpp:74        ] CertificateStore: loaded 2 local certificates.
[1482719575.359|25661|certstore.cpp:205       ] CertificateStore: loaded 0 certificates from /home/<user>/.local/share/ring-kde/certs//.
[1482719575.368|25416|namedirectory.cpp:114   ] Address lookup for <someRingID>: http://ns.ring.cx/addr/<sameRingID>
[1482719575.376|25416|namedirectory.cpp:114   ] Address lookup for <anotherRingID>: http://ns.ring.cx/addr/<sameOtherRingID>
[1482719575.385|25674|certstore.cpp:205       ] CertificateStore: loaded 2 certificates from /usr/share/ca-certificates//trust-source/anchors/.
[1482719575.385|25674|certstore.cpp:205       ] CertificateStore: loaded 0 certificates from /usr/share/ca-certificates//trust-source/blacklist/.
[1482719575.394|25672|certstore.cpp:205       ] CertificateStore: loaded 3 certificates from /usr/share/ca-certificates//.
[1482719575.395|25670|certstore.cpp:205       ] CertificateStore: loaded 3 certificates from /usr/share/ca-certificates//trust-source/.
[1482719575.409|25416|alsalayer.cpp:614       ] card 0 : PCH [HDA Intel PCH]
[1482719575.409|25416|alsalayer.cpp:609       ] Cannot get info for playback device hw:1: No such device or address
```

Ring KDE log:
```
kf5.kcoreaddons.kaboutdata: Could not initialize the equivalent properties of Q*Application: no instance (yet) existing.
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before isSet
QCommandLineParser: call process() or parse() before value
QCommandLineParser: call process() or parse() before values
Updating all accounts
Loading "<accountUID>"
Account parameter " "Account.presenceSubscribeSupported" " not found
Loading "IP2IP"
History doesn't exist or is not readable
Loading vcf from: QDir( "/home/<user>/.local/share/ring-kde/profiles" , nameFilters = { "*" },  QDir::SortFlags( Name | IgnoreCase ) , QDir::Filters( Dirs|Files|Drives|AllEntries ) )
Bookmarks doesn't exist or is not readable
Macros doesn't exist or is not readable
Selection changed 0
Registered Name found. Account: "<accountUID>" status: 3 name: ""
Registered Name found. Account: "<accountUID>" status: 3 name: ""
Selection changed 0
"QColor::setGreen": invalid value -22
"QColor::setBlue": invalid value -38
"QColor::setBlue": invalid value -47
"QColor::setBlue": invalid value -39
"QColor::setBlue": invalid value -40
"QColor::setRed": invalid value -41
"QColor::setBlue": invalid value -12
"QColor::setRed": invalid value -37
"QColor::setBlue": invalid value -41
Constructing DlgProfiles
Ringtones doesn't exist or is not readable
Unknown TLS method "Automatic"
Unknown config properties "lrcfg_zrtpHelloHash"
Unknown config properties "lrcfg_zrtpDisplaySas"
Unknown config properties "lrcfg_zrtpNotSuppWarning"
Unknown config properties "lrcfg_displaySasOnce"
Account parameter " "TLS.listenerPort" " not found
Account parameter " "Account.registrationExpire" " not found
Account parameter " "Account.routeset" " not found
Account parameter " "Account.presenceEnabled" " not found
QObject::connect: invalid null parameter
```

I’ll try GNOME client when I can (maybe tomorrow).

**Comment by moustafine** [comment]
Thanks for your kind advice.
My KDE account is moustafine.

**Comment by tosky** [comment]
moustafine, could you please login into phabricator.kde.org at least once? So you would be able to send reviews and approve them through phabricator.

**Comment by tosky** [comment]
Also, as I'm here and I don't have an AUR account: @ArchangeGabriel , please note that the upstream repository to be used on https://aur.archlinux.org/packages/ring-kde/ is not github.org/KDE/... which is just a mirror, but the official git repository on git.kde.org.
You can use the generic redirect https://commits.kde.org/ring-kde, which is future proof (previously it redirected to quickgit.kde.org, now in cgit.kde.org, probably on phabricator.kde.org in the future).

**Comment by ArchangeGabriel** [comment]
@tosky OK, thanks, fixed. I used GitHub because of the ability to get tarball from specified commit, but I can still use this for source and set the proper url. ;)

**Pull request merged**
