### PR TITLE
Fix account registration via Wizard

### PR DESCRIPTION
**Pull request by moustafine**

### CODE REVIEW

**Comment by Elv13** [comment]
Wow! thanks a lot, I recently had no time for this project. This is greatly welcome. I will compile and test this later today and merge it. As you also probably use Ring-KDE, is there anything outstanding that's broken? I have no friend using Ring, so I don't dogfood this part of the code that much beyond the SIP account support.

**Comment by Elv13** [comment]
Why did you close it?

**Comment by moustafine** [comment]
I read https://community.kde.org/Infrastructure/Github_Mirror.

**Comment by moustafine** [comment]
Then, if i will have something, i will send pull requests here.

**Comment by Elv13** [comment]
Ok, it is merged. I only changed the indentation of a couple of commits to match the project. I have nothing against 2 space indentation and use this in some projects. It is just a question of consistency.

As for "should you use reviewboard or phabricator", technically yes. It could in theory lead to more eyeballs seeing the patches. But the eyeballs will still be mines, so it wont make such a difference. This code was very good and very welcome. I hope you continue to improve the project. Also note that I am willing to eventually transfer my maintainer role to someone willing to push things forward. Ask any questions you might have about the code or architecture directly to me or in an issue. Of course, the code is, in some places, 12 years old and went from Qt3->KDE4->KF5, changed name and started as a dialpad, then a soft-phone, then to become a Skype alternative. This has created some strange things and bitrot, but overall the design is sound, even if it is a little complex in places. The overall direction I moved the project in the last year was to share as much code as possible with the Gnome and OS X clients (also using QtCore) to reduce the maintainer burden and the size of the code. So Ring-KDE is closer to a thin client than ever before. The vast majority of the code is UI related. Some code (for example: the chat) could eventually be pulled from the legacy Windows client (using QtWidgets), but a lot of it is terrible.

**Comment by moustafine** [comment]
I will create new profile with 3 space indentation for this project in QtCreator.
I hope, that I will have time to add some commits to this project and further. And I also hope, that Ring client for KDE sometime in the future will work perfectly. Thanks you for your project.

**Pull request closed without merging**
